### ISSUE TITLE
Make `clang_format_with_style` public

### ISSUE THREAD

**Issue by emilk** [KDAB/clang-format-rs#3]
Hi, thanks for this crate!

Supplying the format via a global (`CLANG_FORMAT_STYLE`) is quite error prone (and a bit ugly).

I suggest making `fn clang_format_with_style` public (and perhaps even remove `fn clang_format` and `CLANG_FORMAT_STYLE` 😬).

**Comment by ahayzen-kdab** [comment]
Thanks for the suggestion, i think that making `clang_format_with_style` would be a good first step.

We currently use `clang_format` and `CLANG_FORMAT_STYLE` in CXX-Qt so that we can set the OnceCell once and then have the same format style for all tests.

However maybe that isn't as beneficial as it seemed originally as
- we don't use `clang_format` in many too places that we could just pass the style in
- clang-format can fallback to the file definition anyway
- now that OnceCell is in std developers could create their own `CLANG_FORMAT_STYLE` removing complexity here.
- for CXX-Qt if we passed it all the time, we then don't need to depend on `ctor` for the tests :-) 

So maybe this could be done as a 0.2 release :-)

**Comment by ahayzen-kdab** [comment]
We've just made a 0.2.0 release with the following changes relevant to this discussion.

-   `clang_format_with_style` method where the style is now public
-   `clang_format` now uses ClangFormatStyle::Default instead of reading from CLANG_FORMAT_STYLE
-  `CLANG_FORMAT_STYLE` oncecell has gone, instead devs can build this themselves if required.

Thank you for the suggestions, please open new issues for any further suggestions or ideas!

**Comment by emilk** [comment]
Thank you! ❤️
